# fly.toml app configuration file generated for maincranto-server on 2025-03-09T13:10:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maincranto-server'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 25565
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 25565
  auto_stop_machines = 'off'
  auto_start_machines = true

  [[services.ports]]
    port = 25565
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
